// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiNL9cRhBWIlQyuZcZCokQAO1SRoDqyb4',
    appId: '1:331919386374:web:21058fc769d7a8494da087',
    messagingSenderId: '331919386374',
    projectId: 'nzimakeeperofnotes',
    authDomain: 'nzimakeeperofnotes.firebaseapp.com',
    storageBucket: 'nzimakeeperofnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIvwkjtc98gDZq3rpzCmmC-Ulr4kpj7k',
    appId: '1:331919386374:android:140f7ae00341d90a4da087',
    messagingSenderId: '331919386374',
    projectId: 'nzimakeeperofnotes',
    storageBucket: 'nzimakeeperofnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeapZ8NkTMRM_YAj9TI0xUYa_Y4ozPHMg',
    appId: '1:331919386374:ios:0b7a37fa799425f94da087',
    messagingSenderId: '331919386374',
    projectId: 'nzimakeeperofnotes',
    storageBucket: 'nzimakeeperofnotes.appspot.com',
    iosClientId: '331919386374-cf072ageake52m2mlbfu12l4jqev5cfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeapZ8NkTMRM_YAj9TI0xUYa_Y4ozPHMg',
    appId: '1:331919386374:ios:0b7a37fa799425f94da087',
    messagingSenderId: '331919386374',
    projectId: 'nzimakeeperofnotes',
    storageBucket: 'nzimakeeperofnotes.appspot.com',
    iosClientId: '331919386374-cf072ageake52m2mlbfu12l4jqev5cfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesKeeper',
  );
}
